import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { StrictMode } from 'react';
import "./globals.css";
import { RccProvider } from './dashboard/RccCalculatorContext';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DXP Tools",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StrictMode>
        <body className={inter.className}>
          <RccProvider>
            {children}
          </RccProvider>
        </body>
      </StrictMode>
    </html>
  );
}